name: Check Commit Status
description: GitHub Action to confirm commit statuses are their expected values.
inputs:
  check:
    description: The status check(s) to validate.
    required: true
  status:
    description: The expected status. Can be 'error', 'failure', 'pending' or 'success'
    default: success
    required: false
  github-token:
    description: The GitHub token to use. Only necessary to set if posting to a different repository.
    required: true
  repo:
    description: The repository to check in. Only necessary to set if posting to a different repository.
    default: ${{ github.repository }}
    required: false
  branch:
    description: The branch to check in. Only necessary to set if posting to a different repository.
    default: ${{ github.head_ref }}
    required: false
outputs:
  success: 
    description: The provided check(s) matches the expected status.
runs:
  using: 'node20'
  main: 'index.js'
